# Generated by Django 4.0 on 2021-12-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_dogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owners',
            name='age',
            field=models.IntegerField(),
        ),
    ]
