# Generated by Django 4.0 on 2021-12-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0003_alter_dogs_age_alter_owners_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dogs',
            new_name='Dog',
        ),
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
    ]
